# -*- coding: utf-8 -*-
"""BMI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpcLq6PIzul4A6zyh5dt4QI6tntmo-N5
"""

def calculate_bmi(weight, height_cm):
    try:
        height_m = height_cm / 100  # Convert height from cm to meters
        bmi = weight / (height_m ** 2)
        return round(bmi, 2)
    except ZeroDivisionError:
        return "Height cannot be zero."

def bmi_category_and_advice(bmi):
    if bmi < 18.5:
        return "Underweight", "Consider eating nutrient-rich foods, increasing your calorie intake, and consulting with a healthcare provider for a personalized plan."
    elif 18.5 <= bmi < 24.9:
        return "Normal weight", "Maintain your healthy weight with a balanced diet and regular physical activity."
    elif 25 <= bmi < 29.9:
        return "Overweight", "Focus on a balanced diet with plenty of fruits and vegetables, watch your portion sizes, and increase your physical activity."
    else:
        return "Obesity", "It's important to consult with a healthcare provider. Aim for a balanced diet, reduced calorie intake, and regular physical activity."

def main():
    print("Welcome to the BMI Calculator!")

    try:
        weight = float(input("Please enter your weight in kilograms: "))
        height_cm = float(input("Please enter your height in centimeters: "))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    bmi = calculate_bmi(weight, height_cm)

    if isinstance(bmi, str):
        print(bmi)
    else:
        category, advice = bmi_category_and_advice(bmi)
        print(f"Your BMI is: {bmi}")
        print(f"This is considered: {category}")
        print(f"Dietary advice: {advice}")

if __name__ == "__main__":
    main()